### ISSUE TITLE
Listening on path that does not exist should return a value with exists = false

### ISSUE THREAD

**Issue by dfirsht** [csync/csync-server#77] opened 2017-03-21 15:41 UTC
Server Version: 1.2.0
Client Version: Any
Steps to Reproduce:
*  Listen on a key with a path that does not exist in the db

Expected Behavior: Return a value with the exists property equals false
Actual Behavior: Nothing

**Comment by kevinlai** [comment] 2017-03-21 15:49
This use case will be resolved by #71

**Comment by mkistler** [comment] 2017-03-22 03:19
I don't believe that the expected behavior is a value with exists = false.  Nothing is actually the correct behavior.  Why?  Because a listen on a key pattern (containing wildcards) cannot give a value with exists = false for every potentially matching key.  Listen on concrete keys should not behave differently than listens on key patterns.

**Comment by boopt2** [comment] 2017-03-27 13:36
Closing this as this it not the functionality we want. Please see #71 for an alternative way of getting this data.

**Closed by boopt2** 2017-03-27 13:36 UTC
